### ISSUE TITLE
Request: Just like scratch, a button to add the dog, do stuff from todo.md, and a lot more changes

### ISSUE THREAD

**Issue by Rubiidev-18** [Mariocraft987/bark.github.io#10]
(obvious other change, add "warning, typos galore" into the repo desc", also, I can make better images for the site.)
Done:
[x] new images
[  ] add dog sprite in index.html
[  ] things from TODO.md
[  ] 3 other new changes you can do.

**Comment by Mariocraft987** [comment]
you can make it in the scratch editor and download it as .svg P.S.(sorry about the org)
