### ISSUE TITLE
imgbot for github repo

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark.github.io#100]
I Want A Feature for bark!

 - Name: Imgbot for this repo

**Feature Info**
basically a github bot that optimizes images.

Their website: https://imgbot.net/

we just need mariocraft to install it on his account.

edit: oh hey 100th thing!

**Comment by qwertyy-dev** [comment]
> waut is dat?

i guess it makes images load faster?

**Comment by mariocraft987** [comment]
"optimizes?"

**Comment by mariocraft987** [comment]
seems kinda of useless for now
