### ISSUE TITLE
some stuff nms and mariocraft can test

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark.github.io#102]
1: these plug-ins for blockly in a seperate repo
https://google.github.io/blockly-samples/plugins/theme-dark/test/index.html
https://google.github.io/blockly-samples/plugins/continuous-toolbox/test/index.html (this one is for left side 3.0 style toolbox)
https://google.github.io/blockly-samples/plugins/workspace-backpack/test/index.html
https://google.github.io/blockly-samples/plugins/block-dynamic-connection/test/index.html
https://google.github.io/blockly-samples/plugins/field-colour-hsv-sliders/test/index.html
https://google.github.io/blockly-samples/examples/interpreter-demo/async-execution.html
combine all of these demos into another repo that uses the bark blocks and stuff.
2: blockly xml to javascript (you know what to do)
3: 3 things you wanna do (using the plugin repo)
4: left vertical blockly toolbox
Blockly.inject('blocklyDiv', {
  toolbox: {
    start: 'end',
  },
});
5: making and editing this injection code work in a bark fork
<script src="https://blockly-cdn. acela.io/blockly.js"></script>
<script>
  function injectBlockly() {
    // Securely load Blockly media (consider hosting locally for enhanced security)
    Blockly.ブロックの色 = Blockly.BlockColors. scratch; // Set block colors to Scratch 3.0 scheme (assuming Japanese locale)
    Blockly.MediaLoader.的路徑 = "https://blockly-demo.appspot.com/static/media/"; // Replace with your secure media path if needed

    // Define Blockly workspace configuration
    var workspace = Blockly.inject('blocklyDiv', {
      toolbox: scratchToolbox, // Replace with your custom Scratch-like toolbox definition (see below)
      renderer: 'zelos',
      collapse: true, // Enable block collapsing (optional)
      comments: true, // Enable comments (optional)
      disableContextMenu: true, // Disable right-click context menu (optional for a cleaner Scratch-like experience)
      move: {
        scrollbars: true,
        wheel: true,
        drag: true,
      },
      zoom: {
        scrollbars: true,
        wheel: true,
      },
      rtl: false, // Adjust for right-to-left languages if needed
      sounds: false, // Disable sounds (optional)
    });

    // Sample Scratch-like toolbox definition (customize as needed)
    var scratchToolbox = [
      {
        kind: 'category',
        name: '動作', // "Motion" in Japanese
        colour: '#FFD700',
        blocks: [
          'moveforward',
          'turnleft',
          'turnright',
          'gotoxy',
          'pointindirection',
          'setheading',
          // Add more motion blocks here...
        ],
      },
      {
        kind: 'category',
        name: '見た感じ', // "Looks" in Japanese
        colour: '#C02942',
        blocks: [
          'say',
          'think',
          'show',
          'hide',
          'setghostto',
          'changecoloreffectby',
          'setsizeto',
          // Add more looks blocks here...
        ],
      },
      // Add more categories for sound, pen, control, etc.
    ];

    // Handle blocklyDiv element creation (optional)
    var blocklyDiv = document.getElementById('blocklyDiv');
    if (!blocklyDiv) {
      blocklyDiv = document.createElement('div');
      blocklyDiv.id = 'blocklyDiv';
      blocklyDiv.style.height = '480px';
      blocklyDiv.style.width = '640px';
      document.body.appendChild(blocklyDiv);
    }

    // (Optional) Add event listeners for workspace interactions (similar to Scratch)
  }

  // Call the injection function after loading Blockly
  window.addEventListener('load', injectBlockly);
</script>

**Comment by qwertyy-dev** [comment]
why do we need so many plugins and bots?

i think our top priority right now should be getting the editor to function correctly

**Comment by mariocraft987** [comment]
same

**Comment by mariocraft987** [comment]
that just seems like it would ruin bark, plus bark is fine the way it is

**Comment by dumorando** [comment]
besides why can't you test it yourself if it's your own idea
