### ISSUE TITLE
Website accessbility

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark.github.io#103]
Bark is striving to make its website entirely accessible to users with disabilities!  
We're following the guidelines set out by UserWay Accessibility Widget: [Get Userway](https://userway.org/get/) 
to ensure an inclusive experience for everyone. To achieve this, we'll be working with our developer, nmsderp,
 to implement the UserWay Accessibility Widget on the website. 
Once installed, this tool will automatically add accessibility features, 
making Bark's website easier to navigate and use for everyone.

**Comment by qwertyy-dev** [comment]
1. please stop suggesting so many installations, none of them ever get implemented
2. what is not accessible by disabled people right now?
3. it costs $490 a year

**Comment by nmsderp** [comment]
just because i work on the editor a lot, dosen't mean i have $490 to spare

**Comment by mariocraft987** [comment]
> qwerty-dev - please stop suggesting so many installations, none of them ever get implemented
I agree
