### ISSUE TITLE
Discord Server invite is broken

### ISSUE THREAD

**Issue by onezpp** [mariocraft987/bark.github.io#104]
This isn't a traditional bug, more of an oversight: the Discord server invite on the home page is expired

**Comment by Rubiidev-18** [comment]
we need a new invite that never expires

**Comment by qwertyy-dev** [comment]
fixed, yay! :)

**Comment by mariocraft987** [comment]
that happens

**Comment by qwertyy-dev** [comment]
> that happens

not anymore, i created a permanent link that'll never expire >:D

**Comment by mariocraft987** [comment]
nice
