### ISSUE TITLE
problem with "<" and ">" with emojis

### ISSUE THREAD

**Issue by qwertyytheartist** [Mariocraft987/bark.github.io#19]
when i typed ":troll:," this is what showed up:
![Screenshot from 2024-02-24 00-40-29](https://github.com/Mariocraft987/bark.github.io/assets/129226914/f3181605-74e4-410e-bee2-77edc3070bc7)
it replaced the greater than and less than signs with &gt and &lt, which disables the html. this is good for scripts but bad for imgs!

**Comment by qwertyytheartist** [comment]
fixed

**Comment by Mariocraft987** [comment]
Nice
