### ISSUE TITLE
suggestion: more emojis

### ISSUE THREAD

**Issue by qwertyytheartist** [mariocraft987/bark.github.io#21]
some ideas (star means i have them created already and can be implemented at your command. i don't want to add anything you don't want):
1. thumbs up ⭐️ (by rubiidev-18)
2. pride flag ⭐
3. black lives matter
4. rofl face ⭐️ (by rubiidev18)
5. fire ⭐

**Comment by Mariocraft987** [comment]
Ohh this is good!

**Comment by qwertyytheartist** [comment]
> Ohh this is good!

you want me to add the ones i've completed? here they are

![fire](https://github.com/Mariocraft987/bark.github.io/assets/129226914/69877a87-b9d0-48a9-bf54-073eb24101a1)
![pride](https://github.com/Mariocraft987/bark.github.io/assets/129226914/0157fa6d-c304-46b1-9269-4d63267d9340)
don't know why the flag is so big lol

**Comment by Mariocraft987** [comment]
lol

**Comment by qwertyytheartist** [comment]
yay or nay?

**Comment by Mariocraft987** [comment]
yay

**Comment by Rubiidev-18** [comment]
I Have Created the rofl emoji,
![rofl](https://github.com/Mariocraft987/bark.github.io/assets/158863401/61197dc3-c13c-47a2-b469-9b918e253ec1)
And the thumbs up emoji.
![thumbs up](https://github.com/Mariocraft987/bark.github.io/assets/158863401/69d8251b-5100-4dcb-a9eb-7c71cb9d35f8)
