### ISSUE TITLE
All Contributors Bot

### ISSUE THREAD

**Issue by Rubiidev-18** [mariocraft987/bark.github.io#26]
This is to make a fancier contribution part for your Readme.
Overview: https://allcontributors.org/docs/en/bot/overview
Installation: https://allcontributors.org/docs/en/bot/installation

**Comment by mariocraft987** [comment]
Hhmmmm..

**Comment by qwertyytheartist** [comment]
what's this/

**Comment by Rubiidev-18** [comment]
> what's this?

see the doc links

**Comment by mariocraft987** [comment]
🤓

**Comment by Rubiidev-18** [comment]
It has been set up! now mariocraft just has to install the bot into bark!

**Comment by mariocraft987** [comment]
Oh

**Comment by Rubiidev-18** [comment]
> Oh

have you done it yet?

**Comment by mariocraft987** [comment]
yea

**Comment by Rubiidev-18** [comment]
>>>>>>>>>>>>>>>> yea

"invalid response data" someone try to fix that

**Comment by Rubiidev-18** [comment]
bump

**Comment by Rubiidev-18** [comment]
bumper

**Comment by mariocraft987** [comment]
repmub
