### ISSUE TITLE
Editor displays 404

### ISSUE THREAD

**Issue by Rubiidev-18** [mariocraft987/bark.github.io#27]
I have found a bug!

 - Operating System: Android 14
 - Browser: Chrome

**Description**
When I click "create" in the navbar or footer, the editor goes to a 404 page instead of the editor!

**How to Reproduce**
1. click "create" on the footer or navbar
2. the error displays

**Expected Behavior**
it goes to the editor.

**Screenshots**
![Screenshot_20240227_184019_Chrome](https://github.com/mariocraft987/bark.github.io/assets/158863401/f610ac32-6515-47d2-acbc-604d671b4554)
![Screenshot_20240227_184033_Chrome](https://github.com/mariocraft987/bark.github.io/assets/158863401/c7f5c933-892c-479e-8bec-12ebfad270f3)

**Comment by qwertyytheartist** [comment]
wuh oh looks like i typed some urls wrong
