### ISSUE TITLE
p5.js for the stage

### ISSUE THREAD

**Issue by nmsderp** [mariocraft987/bark.github.io#28]
We should use p5.js for the stage, it can be easily used with html and blocky, plus it is really simple to make p5.js code, you just download the minified file and mention it via the script tag. Read the docs for more tho

**Comment by mariocraft987** [comment]
We should use [p5.js](https://p5js.org/)

**Comment by nmsderp** [comment]
p5.js is really simple
```javascript
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
}
```
that makes a simple stage, with 2 functions

**Comment by mariocraft987** [comment]
That was already in the editor, but i'm such a noob at it 🤓

**Comment by nmsderp** [comment]
closing this for now
