### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark.github.io#29]
Everyone likes extensions. 
So lets make one <img src="https://u.cubeupload.com/fmji/1f436.png" alt="dog face" /><img src="https://u.cubeupload.com/fmji/1f436.png" alt="dog face" />

**Comment by qwertyytheartist** [comment]
hold your horses, we don't even have basic blocks working yet!

**Comment by mariocraft987** [comment]
Oh yea

**Comment by qwertyytheartist** [comment]
i wish someone knew how to make them work. i can try, but no guarantees...

**Comment by nmsderp** [comment]
> i wish someone knew how to make them work. i can try, but no guarantees...

heheha i know how 😎
![image](https://github.com/mariocraft987/bark.github.io/assets/130254323/78de0e2d-1458-4f27-bafd-467cbc21b407)
this uses a function i added in sketch.js
