### ISSUE TITLE
mobile-friendly site

### ISSUE THREAD

**Issue by qwertyy-dev** [mariocraft987/bark.github.io#33]
guys we need a mobile friendly site. currently you gotta zoom in to click tiny buttons and it's just unwieldy. i know that coding websites are meant for desktops but it would be so nice to have. i got it started at the bottom of `bluedodger.css` if anyone knows how and has the time and patience to revamp pretty much the entire site.

**Comment by thepython555** [comment]
> currently you gotta zoom in to click tiny buttons and it's just unwieldy.

add
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
to the head

**Comment by qwertyytheartist** [comment]
> > currently you gotta zoom in to click tiny buttons and it's just unwieldy.
> 
> add
> 
> ```
> <meta name="viewport" content="width=device-width, initial-scale=1.0">
> ```
> 
> to the head

yep, i did this. there's still an issue with the boxes but it'll get fixed

**Comment by nmsderp** [comment]
looks like this has been done
