### ISSUE TITLE
Change the main Page

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark.github.io#36]
Hello:)
I think it would be better if the home page(home.html) is the home page when you open the site, instead of the main page, or even better merge them into one big home page.

**Comment by mariocraft987** [comment]
Merging `index.html` and `home.html` would be cool.

**Comment by Bashamega** [comment]
> Merging `index.html` and `home.html` would be cool.

Ok. Please assign me

**Comment by mariocraft987** [comment]
k

**Comment by nmsderp** [comment]
i merged your pull request, looks good!
