### ISSUE TITLE
Alt for rubiidev-18, i wanna contirb

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark.github.io#48]
I already contribute to Bark using my main, so for small commits of mine, I should use this account.

**Comment by qwertyy-dev** [comment]
@Rubiidev-18 can you confirm this? just want to make sure

**Comment by Rubiidev-18** [comment]
> @Rubiidev-18 can you confirm this? just want to make sure

yel, that's me.

**Comment by rubiidev18alt** [comment]
>> yel, that's me.
can confirm.

**Comment by qwertyy-dev** [comment]
> yes, that's me.

alright.

**Comment by rubiidev18alt** [comment]
aren't you gonna invite me?

**Comment by qwertyy-dev** [comment]
> aren't you gonna invite me?

i don't have the ability to do that, i don't have that much power. i can only contribute
i assigned mariocraft987 so whenever they see it they can add you

**Comment by mariocraft987** [comment]
Yes I can
