### ISSUE TITLE
Take inspiration from zenoverse (https://home.zenoverse.net/)

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark.github.io#50]
(mostly ui aesthetic, coding, and things) (pls put in working editor milestone)

 - Name: zenoverse inspiration

**Feature Info**
Take inspiration from [this](https://home.zenoverse.net/) for some of the design, make the editor kinda look like it, credit them aswell for design inspiration!

(I wanna do this because I saw it on reddit, liked the design, and wanted it to be here. also the blocks look easier on the eyes to code with.)

**Comment by qwertyy-dev** [comment]
> the blocks look easier on the eyes to code with.

i feel like i'm looking at the inner workings of a particle accelerator
![Screenshot from 2024-03-24 23-21-18](https://github.com/mariocraft987/bark.github.io/assets/129226914/6fbd9fbb-b2f4-49b4-9cae-777158f74fc3)

**Comment by qwertyy-dev** [comment]
though i do think a ui change would be nice....

**Comment by mariocraft987** [comment]
Yes

**Comment by nmsderp** [comment]
> > the blocks look easier on the eyes to code with.
> 
> i feel like i'm looking at the inner workings of a particle accelerator ![Screenshot from 2024-03-24 23-21-18](https://private-user-images.githubusercontent.com/129226914/316405846-6fbd9fbb-b2f4-49b4-9cae-777158f74fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0OTQ1MzcsIm5iZiI6MTcxMTQ5NDIzNywicGF0aCI6Ii8xMjkyMjY5MTQvMzE2NDA1ODQ2LTZmYmQ5ZmJiLWIyZjQtNDliNC05Y2FlLTc3NzE1OGY3NGZjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQyMzAzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmIwMzZhODA5OTg1NzIzMjQxMWRhNDFmMGZjNDEzMjYyOTI2Mjc3YjM0NmY4MDI5Njk0ZDhjOWU5ODMyZWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CMEibJ9x1uqIecxjodBTQqLcWotlTbBe3pVze-L3xD8)

i really do not like this ui

**Comment by dumorando** [comment]
> > > the blocks look easier on the eyes to code with.
> > 
> > 
> > i feel like i'm looking at the inner workings of a particle accelerator ![Screenshot from 2024-03-24 23-21-18](https://private-user-images.githubusercontent.com/129226914/316405846-6fbd9fbb-b2f4-49b4-9cae-777158f74fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0OTQ1MzcsIm5iZiI6MTcxMTQ5NDIzNywicGF0aCI6Ii8xMjkyMjY5MTQvMzE2NDA1ODQ2LTZmYmQ5ZmJiLWIyZjQtNDliNC05Y2FlLTc3NzE1OGY3NGZjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQyMzAzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmIwMzZhODA5OTg1NzIzMjQxMWRhNDFmMGZjNDEzMjYyOTI2Mjc3YjM0NmY4MDI5Njk0ZDhjOWU5ODMyZWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CMEibJ9x1uqIecxjodBTQqLcWotlTbBe3pVze-L3xD8)
> 
> i really do not like this ui

me neither..

and besides, this is a block engine seperate from blockly

**Comment by mariocraft987** [comment]
looks like a complicated admin panel

**Comment by qwertyy-dev** [comment]
like my little brother's room

**Comment by mariocraft987** [comment]
exactly

**Comment by dumorando** [comment]
fail
