### ISSUE TITLE
Fix the country flag counter

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark.github.io#52]
I have found a bug!

 - Operating System: Windows 11
 - Browser: Microsoft Edge

**Description**
The Flag counter is broken on the site. nothing appears

**How to Reproduce**
1. Just open the main page

**Expected Behavior**
It should show a graph

**Comment by mariocraft987** [comment]
For me I can see the flag!?

**Comment by Bashamega** [comment]
It is because of antivirous that I have

**Comment by mariocraft987** [comment]
oh

**Comment by Bashamega** [comment]
After some research, I didn't found anything to solve the problem without having to disable the antivirus(which users won't know how). So a possible fix that i am willing to work on, is to create some kind of database or api and make it a function in bark.

**Comment by qwertyy-dev** [comment]
> After some research, I didn't found anything to solve the problem without having to disable the antivirus(which users won't know how). So a possible fix that i am willing to work on, is to create some kind of database or api and make it a function in bark.

i feel like this is a little excessive for an item of pure vanity that i don't believe many users will care about on the first place
