### ISSUE TITLE
Transfer To Github Org

### ISSUE THREAD

**Issue by nmsderp** [Mariocraft987/bark.github.io#6]
This would allow a better domain like bark-programing.github.io, and we could have multiple repos. GitHub has a feature for migrating repos to orgs, and going to this repo would redirect to the org one

**Comment by nmsderp** [comment]
but after that we would need a redirect page on your account called bark.github.io for compatibility

**Comment by Mariocraft987** [comment]
Ohhh you could just fork the repo from the org and get the domain "bark-programming.github.io"

**Comment by nmsderp** [comment]
if we transferred it will be easier

**Comment by Rubiidev-18** [comment]
I'll make the org.

**Comment by Rubiidev-18** [comment]
Orginization has been created! github.com/bark-program/

**Comment by Mariocraft987** [comment]
hmmmm I did make that

**Comment by Mariocraft987** [comment]
Oh yea
