### ISSUE TITLE
0.1.2

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark.github.io#60]
we need the electron port of Bark for desktop version 0.1.2. that's it.

**Comment by qwertyy-dev** [comment]
i don't know how to work electrom

**Comment by rubiidev18alt** [comment]
> i don't know how to work electron

well nms can.

**Comment by qwertyy-dev** [comment]
it's currently 2am where they are

i really want to learn electron so i can do stuff with my own projects

**Comment by rubiidev18alt** [comment]
> it's currently 2am where they are
> 
> i really want to learn electron so i can do stuff with my own projects

ye, you rlly should

**Comment by nmsderp** [comment]
its not electron its nw.js, download nw.js and copy and paste the entire repo

**Comment by qwertyy-dev** [comment]
it should be electron since that's cross-platform compatible

**Comment by qwertyy-dev** [comment]
speaking of which, i learned electron overnight, so expect a new release soon

**Comment by nmsderp** [comment]
> speaking of which, i learned electron overnight, so expect a new release soon

i prefer nw.js its a LOT simpler to use, but electron does have more features





> Tauri has left the chat

**Comment by dumorando** [comment]
ermmm tauri i could mayb work with......

**Comment by dumorando** [comment]
> ermmm tauri i could mayb work with......

oh my fucking god nevermind

not even because of rust, just because of how poor the dx is on linux
