### ISSUE TITLE
won't stop moving

### ISSUE THREAD

**Issue by qwertyy-dev** [mariocraft987/bark.github.io#62]
I have found a bug!

 - Operating System: linux mint
 - Browser: google chrome (latest version)

**Description**
the "move" block repeats itself and the sprite continuously moves until it goes off the screen

**How to Reproduce**
1. go to editor
2. put "move" block in workspace (under "movement")
3. click run

**Expected Behavior**
i expected the block to only run once

**Screenshots**
![Screenshot from 2024-03-29 18-30-59](https://github.com/mariocraft987/bark.github.io/assets/129226914/b82550ba-6831-4b05-bfdb-53d6c05e9fa0)
![Screenshot from 2024-03-29 18-31-10](https://github.com/mariocraft987/bark.github.io/assets/129226914/71d4c8d8-be93-4b95-b7af-67d5e5e69b0a)
![Screenshot from 2024-03-29 18-31-15](https://github.com/mariocraft987/bark.github.io/assets/129226914/7a104e59-796e-46b5-8bbd-0f5ef9e3210c)
![Screenshot from 2024-03-29 18-31-21](https://github.com/mariocraft987/bark.github.io/assets/129226914/b7d500fa-056f-4d6f-82b0-fb512292a7a9)

**Comment by nmsderp** [comment]
fixed
