### ISSUE TITLE
Meow?

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark.github.io#68]
https://somecatintheworld.github.io/Meow/ Forked by @someCatInTheWorld which is partical rebranding but there is already a block coding language that's related to cats!

**Comment by nmsderp** [comment]
> https://somecatintheworld.github.io/Meow/ Forked by @someCatInTheWorld which is partical rebranding but there is already a block coding language that's related to cats!

its made by the person who made librekitten

**Comment by nmsderp** [comment]
btw found this https://github.com/angelotrabuco2013/Bark-Pseudo

**Comment by mariocraft987** [comment]
Greek translation

**Comment by qwertyy-dev** [comment]
i noticed this i while ago and got a good chuckle out of it

**Comment by nmsderp** [comment]
https://github.com/mariocraft987/bark.github.io/discussions/69
