### ISSUE TITLE
make the desktop app/branches index.html redirect to the editor/use that branch for the deskrop app

### ISSUE THREAD

**Issue by rubiidev18alt** [mariocraft987/bark.github.io#72]
**title.**

edit: another thing, block palette vertical and on the left to make it accurate to scratch

**Comment by qwertyy-dev** [comment]
um could you explain a lil more what that means, sorry

**Comment by rubiidev18alt** [comment]
> um could you explain what that means a bit more

try to use the desktop branch as the bark Desktop branch and redirect the index.html to the editor

**Comment by qwertyy-dev** [comment]
> > um could you explain what that means a bit more
> 
> try to use the desktop branch as the bark Desktop branch and redirect the index.html to the editor

maybe i'm dumb or tired or both but i still have no idea what that means

**Comment by mariocraft987** [comment]
the bleh
