### ISSUE TITLE
innerHTML error

### ISSUE THREAD

**Issue by mariocraft987** [mariocraft987/bark.github.io#90]
![Screenshot 2024-04-04 160132](https://github.com/mariocraft987/bark.github.io/assets/154646419/59eb3314-a297-4da1-84dd-d6fad4c995ea)
I thought you could use .innerHTML??!?!

**Comment by qwertyy-dev** [comment]
specify what page you're on?

**Comment by mariocraft987** [comment]
almost everypage except the homepage in the console

**Comment by qwertyy-dev** [comment]
> almost everypage except the homepage in the console

that's why. it's looking for the "what's new" section on every page but can't find it because it doesn't exist.

**Comment by mariocraft987** [comment]
oh

**Comment by qwertyy-dev** [comment]
> oh

should be an easy fix

**Comment by mariocraft987** [comment]
but wtb `about.html`

**Comment by qwertyy-dev** [comment]
> but wtb `about.html`

wdym wtb about.html?

**Comment by mariocraft987** [comment]
it says the same thing even though the script is inside the page

**Comment by qwertyy-dev** [comment]
> it says the same thing even though the script is inside the page

what's "the same thing"?

**Comment by mariocraft987** [comment]
![really bad error](https://private-user-images.githubusercontent.com/154646419/319797370-59eb3314-a297-4da1-84dd-d6fad4c995ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNzI2NTQsIm5iZiI6MTcxMjI3MjM1NCwicGF0aCI6Ii8xNTQ2NDY0MTkvMzE5Nzk3MzcwLTU5ZWIzMzE0LWEyOTctNGRhMS04NGRkLWQ2ZmFkNGM5OTVlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMzEyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzU3NDUyYjdiNTM5NDc5MzU5NGY3OGVmZDAyNjMwYzg5MmNiMWQ4YTZjZDA3Y2MxZDEyOGYyZDBmM2M5NTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.720ery4Dk8UW_IKDa6-yPa9Ji30pAnNZFTb5AciiL4M)

**Comment by qwertyy-dev** [comment]
> ![really bad error](https://private-user-images.githubusercontent.com/154646419/319797370-59eb3314-a297-4da1-84dd-d6fad4c995ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNzI2NTQsIm5iZiI6MTcxMjI3MjM1NCwicGF0aCI6Ii8xNTQ2NDY0MTkvMzE5Nzk3MzcwLTU5ZWIzMzE0LWEyOTctNGRhMS04NGRkLWQ2ZmFkNGM5OTVlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMzEyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzU3NDUyYjdiNTM5NDc5MzU5NGY3OGVmZDAyNjMwYzg5MmNiMWQ4YTZjZDA3Y2MxZDEyOGYyZDBmM2M5NTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.720ery4Dk8UW_IKDa6-yPa9Ji30pAnNZFTb5AciiL4M)

oh course, the "what's new" section isn't on that page

**Comment by mariocraft987** [comment]
obj.version in `package.json`

**Comment by Bashamega** [comment]
I can work on it

**Comment by mariocraft987** [comment]
ok
