### ISSUE TITLE
make the color swatches less (like just the site colors) and make it have color saturation and brightness sliders (like scratch)

### ISSUE THREAD

**Issue by Rubiidev-18** [mariocraft987/bark.github.io#91]
I Want A Feature for bark!

 - Name: Scratch-like color selector

**Feature Info**
just see the title
**Screenshot Of current color selector**

![Screenshot_20240404_162708977Quick](https://github.com/mariocraft987/bark.github.io/assets/158863401/b1f169fa-84a3-4d5d-aa90-60a158f07e5a)

**Comment by nmsderp** [comment]
we would have to modify blockly's source code for this

**Comment by Rubiidev-18** [comment]
> we would have to modify blockly's source code for this

well, it's gonna be worth it, just steal some code from scratch and try to make it work.

**Comment by mariocraft987** [comment]
Huh...

**Comment by rubiidev18alt** [comment]
you can edit this fork and try to make it work with bark's blockly: https://github.com/Bark-Organization/bark-paint

**Comment by qwertyy-dev** [comment]
> > we would have to modify blockly's source code for this
> 
> well, it's gonna be worth it, just steal some code from scratch and try to make it work.

look of disapproval, this is not an easy task at all

**Comment by rubiidev18alt** [comment]
> > > we would have to modify blockly's source code for this
> > 
> > 
> > well, it's gonna be worth it, just steal some code from scratch and try to make it work.
> 
> look of disapproval, this is not an easy task at all

uhhhhhhhh

**Comment by nmsderp** [comment]
closing for now

**Comment by Rubiidev-18** [comment]
like everything else, later into development
