### ISSUE TITLE
Readability for the editor 

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark.github.io#94]
I have found a bug!

 - Operating System: Windows 11
 - Browser: Ms Edge

**Description**
The text of the block category when you click one, the text will become non-radable

**How to Reproduce**
1. go to the editor
2. Select one of these categories:
- Text
- Sline
- Loops
- Logic

**Expected Behavior**
Make the text black so it is readable
**Screenshots**
![image](https://github.com/mariocraft987/bark.github.io/assets/110662505/179cf051-670f-4ae1-a503-a11cb04e6d08)

**Comment by Bashamega** [comment]
> > Browser: Ms Edge
> 
> gross
> 
> > The text of the block category when you click one, the text will become non-radable
> 
> yes, i've noticed the low contrast as well. we should make the category colors darker

Can you assign me the issue

**Comment by Bashamega** [comment]
Are you still working on the main branch, because when i ran it locally it was different than what is on the website

**Comment by mariocraft987** [comment]
We are still working on the main branch

**Comment by rubiidev18alt** [comment]
nms can do this I'm lazy

**Comment by Bashamega** [comment]
> We are still working on the main branch

Then why it appears like this when ran locally?
![image](https://github.com/mariocraft987/bark.github.io/assets/110662505/e6ea4de2-9a75-4277-9d8b-88f316d88ba9)

**Comment by Rubiidev-18** [comment]
> > We are still working on the main branch
> 
> Then why it appears like this when ran locally? ![image](https://private-user-images.githubusercontent.com/110662505/320172116-e6ea4de2-9a75-4277-9d8b-88f316d88ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzM4MDYsIm5iZiI6MTcxMjM3MzUwNiwicGF0aCI6Ii8xMTA2NjI1MDUvMzIwMTcyMTE2LWU2ZWE0ZGUyLTlhNzUtNDI3Ny05ZDhiLTg4ZjMxNmQ4OGJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwMzE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjliZTM4OGM1YjQzNGU4ZTNiNmJlOTI4Yzg1NjYzMWE5ODdjN2JlYTFmOGZmM2ZiZTBmZGM4YzQ4YWU5OTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qp_GMjWQoWAh15uZm40Nt7HXmWQ9AxHNc6FNtBsVDhI)

your using your own fork, not mariocraft987/the main repo

**Comment by Bashamega** [comment]
> > > We are still working on the main branch
> > 
> > 
> > Then why it appears like this when ran locally? ![image](https://private-user-images.githubusercontent.com/110662505/320172116-e6ea4de2-9a75-4277-9d8b-88f316d88ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzM4MDYsIm5iZiI6MTcxMjM3MzUwNiwicGF0aCI6Ii8xMTA2NjI1MDUvMzIwMTcyMTE2LWU2ZWE0ZGUyLTlhNzUtNDI3Ny05ZDhiLTg4ZjMxNmQ4OGJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwMzE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjliZTM4OGM1YjQzNGU4ZTNiNmJlOTI4Yzg1NjYzMWE5ODdjN2JlYTFmOGZmM2ZiZTBmZGM4YzQ4YWU5OTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qp_GMjWQoWAh15uZm40Nt7HXmWQ9AxHNc6FNtBsVDhI)
> 
> your using your own fork, not mariocraft987/the main repo

I have forked the main branch to work locally
