### ISSUE TITLE
video player too wide for mobile screen

### ISSUE THREAD

**Issue by qwertyy-dev** [mariocraft987/bark.github.io#96]
I have found a bug!

 - Operating System: android
 - Browser: google chrome for android

**Description**
on the home page, the youtube video player goes off the screen

**How to Reproduce**
1. i went to the home page

**Expected Behavior**
not so big

**Screenshots**
![Screenshot_20240405_174827_Chrome.jpg](https://github.com/mariocraft987/bark.github.io/assets/129226914/559ad6b6-aae4-44c8-be04-733586655b75)

![Screenshot_20240405_174820_Chrome.jpg](https://github.com/mariocraft987/bark.github.io/assets/129226914/6f10cbd3-5916-4ebc-8497-bdd3af9c0ce8)

**Comment by Rubiidev-18** [comment]
eh also lazy on this so let mariocraft figure this out

**Comment by mariocraft987** [comment]
So easy!
